### ISSUE TITLE
Cannot modify header information - headers already sent by (output started at phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php:172)

### ISSUE THREAD

**Issue by vsalvans** [fmalk/codeigniter-phpunit#23]
Hi,

When I run phpunit, I've got this error:

.<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php:172)</p>
<p>Filename: libraries/Session.php</p>
<p>Line Number: 676</p>

</div>.

It runs ok but it prints out this message which it's quite annoying.

I've got no idea what coult it be.

Thanks!

**Comment by javiernunez** [comment]
Hi VSlavans, i had the same problem. This is easily solved changing the errors output, by executing the command like this:

```
$ phpunit --stderr
```

I have set a pull request in order to change that in config file

**Comment by fmalk** [comment]
@javiernunez I think the problem with this solution is, if in the future you have a failing test, one that throws something undetected, you could potentially lose tracking of that because you're not aware of what goes to `stderr`. Also, if one of you test class actually prints something that needs to be asserted, you can't do that with `stderr`.
It can be a drag, because PHP, CI, etc, so many things tend to write to output buffer ahead of time, but the actual solution is to decouple to a higher degree what you're trying to test, so it won't try to print to headers while doing that.

**Comment by johnmwenda** [comment]
``` hehe ````
