### ISSUE TITLE
Not working in Ubuntu server 12.04

### ISSUE THREAD

**Issue by eoanlabs** [fmalk/codeigniter-phpunit#4]
Hi,

I tried following the instruction, and somehow it was successfull in my Windows 8.1 laptop, but when I tried the same in Ubuntu server 12.04-64 bit it only shows welome.

CodeIgniter v2.1.4
Even with PHPUnit 4.0.x or 3.7.x, its till the same

Please see attached screenshot below. The gray is an ssh remote terminal into the ubuntu server.

![codeigniter-phpunit](https://cloud.githubusercontent.com/assets/2394220/2600371/d07357d6-bafc-11e3-8922-755b8db63711.png)

P.S. I also tried on another ubuntu 12.04 server, and the result is the same

**Comment by grantgeorge** [comment]
@fmalk hey there! Stumbled upon this thread because I'm getting the same warnings.

I believe the latest version of phpunit is 4.5.0 which might be related to the issue. I'm going to install PHPUnit: 3.7.x (up 3.7.34) per your suggestion and try again. I'll try to leave an update here in case it helps anyone else down the road :)

**Comment by grantgeorge** [comment]
getting the same result using PHPUnit 3.7.34 : /

I wonder if it has to do with the version of CI. Our application is on 2.1.3. I manually went in and updated system/core/CodeIgniter.php based on the diff you provide in the readme.
